export const varietyOptions = [
  { key: 'ba', value: 'Barbera', text: 'Barbera' },
  { key: 'bl', value: 'Blaufränkisch', text: 'Blaufränkisch' },
  { key: 'ct', value: 'Cabernet', text: 'Cabernet' },
  { key: 'cr', value: 'Carmenère', text: 'Carmenère' },
  { key: 'ch', value: 'Champagne', text: 'Champagne' },
  { key: 'cy', value: 'Chardonnay', text: 'Chardonnay' },
  { key: 'cb', value: 'Chenin Blanc', text: 'Chenin Blanc' },
  { key: 'fi', value: 'Fiano', text: 'Fiano' },
  { key: 'fr', value: 'Friulano', text: 'Friulano' },
  { key: 'gs', value: 'G-S-M', text: 'G-S-M' },
  { key: 'ga', value: 'Gamay', text: 'Gamay' },
  { key: 'gb', value: 'Grenache Blanc', text: 'Grenache Blanc' },
  { key: 'me', value: 'Melon', text: 'Melon' },
  { key: 'mt', value: 'Merlot', text: 'Merlot' },
  { key: 'ml', value: 'Monastrell', text: 'Monastrell' },
  { key: 'nm', value: 'Nerello Mascalese', text: 'Nerello Mascalese' },
  { key: 'ps', value: 'Petite Sirah', text: 'Petite Sirah' },
  { key: 'pn', value: 'Pinot Nero', text: 'Pinot Nero' },
  { key: 'nr', value: 'Pinot Noir', text: 'Pinot Noir' },
  { key: 'pr', value: 'Portuguese Red', text: 'Portuguese Red' },
  { key: 'pw', value: 'Portuguese White', text: 'Portuguese White' },
  { key: 'rb', value: 'Red Blend', text: 'Red Blend' },
  { key: 'rg', value: 'Riesling', text: 'Riesling' },
  { key: 'rs', value: 'Rosé', text: 'Rosé' },
  { key: 're', value: 'Roussanne', text: 'Roussanne' },
  { key: 'sa', value: 'Sangiovese', text: 'Sangiovese' },
  { key: 'sv', value: 'Sauvignon', text: 'Sauvignon' },
  { key: 'sh', value: 'Sherry', text: 'Sherry' },
  { key: 'sz', value: 'Shiraz', text: 'Shiraz' },
  { key: 'sy', value: 'Syrah', text: 'Syrah' },
  { key: 'ta', value: 'Tannat', text: 'Tannat' },
  { key: 'te', value: 'Tempranillo', text: 'Tempranillo' },
  { key: 'tu', value: 'Turbiana', text: 'Turbiana' },
  { key: 've', value: 'Verdicchio', text: 'Verdicchio' },
  { key: 'zn', value: 'Zinfandel', text: 'Zinfandel' },
]

export const countryOptions = [
  { key: 'ar', value: 'Argentina', text: 'Argentina' },
  { key: 'am', value: 'Armenia', text: 'Armenia' },
  { key: 'au', value: 'Australia', text: 'Australia' },
  { key: 'at', value: 'Austria', text: 'Austria' },
  {
    key: 'ba',
    value: 'Bosnia and Herzegovina',
    text: 'Bosnia and Herzegovina',
  },
  { key: 'br', value: 'Brazil', text: 'Brazil' },
  { key: 'bg', value: 'Bulgaria', text: 'Bulgaria' },
  { key: 'ca', value: 'Canada', text: 'Canada' },
  { key: 'cl', value: 'Chile', text: 'Chile' },
  { key: 'cn', value: 'China', text: 'China' },
  { key: 'hr', value: 'Croatia', text: 'Croatia' },
  { key: 'cy', value: 'Cyprus', text: 'Cyprus' },
  { key: 'cz', value: 'Czech Republic', text: 'Czech Republic' },
  { key: 'eg', value: 'Egypt', text: 'Egypt' },
  { key: 'gb', value: 'England', text: 'England' },
  { key: 'fr', value: 'France', text: 'France' },
  { key: 'ge', value: 'Georgia', text: 'Georgia' },
  { key: 'de', value: 'Germany', text: 'Germany' },
  { key: 'gr', value: 'Greece', text: 'Greece' },
  { key: 'hu', value: 'Hungary', text: 'Hungary' },
  { key: 'in', value: 'India', text: 'India' },
  { key: 'il', value: 'Israel', text: 'Israel' },
  { key: 'it', value: 'Italy', text: 'Italy' },
  { key: 'lb', value: 'Lebanon', text: 'Lebanon' },
  { key: 'lu', value: 'Luxembourg', text: 'Luxembourg' },
  { key: 'mk', value: 'Macedonia', text: 'Macedonia' },
  { key: 'mg', value: 'Madagascar', text: 'Madagascar' },
  { key: 'mx', value: 'Mexico', text: 'Mexico' },
  { key: 'md', value: 'Moldova', text: 'Moldova' },
  { key: 'ma', value: 'Morocco', text: 'Morocco' },
  { key: 'nz', value: 'New Zealand', text: 'New Zealand' },
  { key: 'pe', value: 'Peru', text: 'Peru' },
  { key: 'pt', value: 'Portugal', text: 'Portugal' },
  { key: 'ro', value: 'Romania', text: 'Romania' },
  { key: 'se', value: 'Serbia', text: 'Serbia' },
  { key: 'sk', value: 'Slovakia', text: 'Slovakia' },
  { key: 'sl', value: 'Slovenia', text: 'Slovenia' },
  { key: 'za', value: 'South Africa', text: 'South Africa' },
  { key: 'es', value: 'Spain', text: 'Spain' },
  { key: 'ch', value: 'Switzerland', text: 'Switzerland' },
  { key: 'tr', value: 'Turkey', text: 'Turkey' },
  { key: 'ua', value: 'Ukraine', text: 'Ukraine' },
  { key: 'uy', value: 'Uruguay', text: 'Uruguay' },
  { key: 'us', value: 'US', text: 'US' },
]

export const flavors = [
  { key: 'ac', value: 'acid', text: 'acid' },
  { key: 'bo', value: 'body', text: 'body' },
  { key: 'br', value: 'brettanomyces', text: 'brettanomyces' },
  { key: 'ca', value: 'caramel', text: 'caramel' },
  { key: 'co', value: 'complexity', text: 'complexity' },
  { key: 'fl', value: 'flower', text: 'flower' },
  { key: 'fr', value: 'fruit', text: 'fruit' },
  { key: 'nu', value: 'nutty', text: 'nutty' },
  { key: 'sa', value: 'salinity', text: 'salinity' },
  { key: 'sp', value: 'spice', text: 'spice' },
  { key: 'sw', value: 'sweetness', text: 'sweetness' },
  { key: 'ta', value: 'tannin', text: 'tannin' },
  { key: 've', value: 'vegetal', text: 'vegetal' },
  { key: 'wo', value: 'woody', text: 'woody' },
]

export const colorOptions = [
  { key: 'red', text: 'Reds', value: 'red' },
  { key: 'white', text: 'Whites', value: 'white' },
  { key: 'rose', text: 'Rose', value: 'rose' },
]

export const maxPriceOptions = [
  // { key: '9999', text: 'No Max Limit', value: '' },
  { key: '2000', text: 'Less than $2000', value: 1999 },
  { key: '1000', text: 'Less than $1000', value: 999 },
  { key: '500', text: 'Less than $500', value: 499 },
  { key: '250', text: 'Less than $250', value: 249 },
  { key: '100', text: 'Less than $100', value: 99 },
  { key: '75', text: 'Less than $75', value: 74 },
  { key: '50', text: 'Less than $50', value: 49 },
  { key: '25', text: 'Less than $25', value: 24 },
]

export const minPriceOptions = [
  // { key: '0', text: 'No Min Limit', value: '' },
  { key: '25', text: 'Greater than $25', value: 25 },
  { key: '50', text: 'Greater than $50', value: 50 },
  { key: '75', text: 'Greater than $75', value: 75 },
  { key: '100', text: 'Greater than $100', value: 100 },
  { key: '250', text: 'Greater than $250', value: 250 },
  { key: '500', text: 'Greater than $500', value: 500 },
  { key: '1000', text: 'Greater than $1000', value: 1000 },
  { key: '2000', text: 'Greater than $2000', value: 2000 },
]
